In [1]:
import numpy as np
import tensorflow as tf
import time
from tensorflow.keras import layers
from sklearn.metrics import f1_score
import os

2023-06-05 13:46:22.450201: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.


In [3]:
# Load the dataset
#data_path = '/Users/as274094/Documents/psf_dataset1/'
#data_path = '/gpfswork/rech/prk/uzk69cg/psf_dataset1/'
data_path = '/Users/as274094/GitHub/Refractored_star_classifier/tensorflow_version/'
dataset = np.load(data_path + 'PCA_dataset1.npy', allow_pickle=True)[()]

x_train = dataset['train_stars_pca']
x_val = dataset['validation_stars_pca']
x_test = dataset['test_stars_pca']
y_train = dataset['train_C']
y_val = dataset['validation_C']
y_test = dataset['test_C']
SED_test = dataset['test_SEDs']


In [4]:
# Hyperparameters
PCA_components = 24
model_learning_rate = 0.1
N_epochs = 10
N_committee = 48
patience_epochs = 3

In [5]:
def SEDlisttoC(SED_list):
    sed_array = np.array(SED_list)
    return sed_array*0.5 + 1.5

def CtoSEDarray(c_values, variance):
    sed_classes = ((c_values - 1.25) // 0.5).astype(int)
    sed_classes = np.where((c_values < 1.25) | (c_values > 7.75), 20, sed_classes)
    sed_classes = np.where((variance > 1.00), 20, sed_classes)
    return sed_classes

def calculate_success_rate(confusion_matrix):
    diagonal = np.trace(confusion_matrix)
    diagonal_neighbors = np.sum(np.diagonal(confusion_matrix, offset=1)) + np.sum(np.diagonal(confusion_matrix, offset=-1))
    total_classified = np.sum(confusion_matrix)
    
    success_rate = (diagonal + diagonal_neighbors) / total_classified
    return success_rate

In [15]:
# Define the model architecture
def create_model():
    initializer = tf.keras.initializers.GlorotNormal(seed = None)
    model = tf.keras.Sequential([
        layers.Dense(26, input_shape=[PCA_components], activation='sigmoid', kernel_initializer= initializer),
        layers.Dense(26, activation='sigmoid', kernel_initializer= initializer),
        layers.Dense(1, activation = 'linear', kernel_initializer= initializer)
    ])
    model.compile(
        loss = tf.keras.losses.MeanSquaredError(),
        optimizer = tf.keras.optimizers.Adam(learning_rate = model_learning_rate)
    )
    return model

class TrainingCompletionCallback(tf.keras.callbacks.Callback):
    def on_train_end(self, logs=None):
        epochs = len(self.model.history.history['loss'])
        final_loss = self.model.history.history['loss'][-1]
        final_val_loss = self.model.history.history['val_loss'][-1]

        print("Training completed. Number of epochs:", epochs, ", Final training loss:", final_loss, ", Final validation loss:", final_val_loss)

early_stopping = tf.keras.callbacks.EarlyStopping(monitor = "val_loss", patience = patience_epochs, restore_best_weights=True)
completion_callback = TrainingCompletionCallback()

start_time = time.time() # Measure training time

# Train a committee of 48 neural networks
committee = []
for i in range(N_committee):
    model = create_model()
    print("Training network #",i)
    learning = model.fit(x_train, y_train, epochs= N_epochs, verbose = 0, callbacks = [completion_callback, early_stopping], validation_data=(x_val,y_val))
    committee.append(model)   

# Calculate the training time
end_time = time.time()
training_time = end_time - start_time
print("Total training time:", training_time, "seconds")


Training network # 0
Training completed. Number of epochs: 5 , Final training loss: 6.388964653015137 , Final validation loss: 6.3534255027771
Training network # 1
Training completed. Number of epochs: 5 , Final training loss: 6.388964653015137 , Final validation loss: 6.353425979614258
Training network # 2
Training completed. Number of epochs: 5 , Final training loss: 6.388964653015137 , Final validation loss: 6.353425025939941
Training network # 3
Training completed. Number of epochs: 5 , Final training loss: 6.3889641761779785 , Final validation loss: 6.3534255027771
Training network # 4
Training completed. Number of epochs: 5 , Final training loss: 6.388964653015137 , Final validation loss: 6.353425979614258
Training network # 5
Training completed. Number of epochs: 5 , Final training loss: 6.388964653015137 , Final validation loss: 6.353425979614258
Training network # 6
Training completed. Number of epochs: 5 , Final training loss: 6.388964653015137 , Final validation loss: 6.3534

In [ ]:
# Load a trained committee

committee = []
committee_path = '/Users/as274094/GitHub/Refractored_star_classifier/tensorflow_version/committee_models'
# Load each model in the committee
for i in range(N_committee):
    model_path = os.path.join(committee_path, f'model_{i}.h5')
    loaded_model = tf.keras.models.load_model(model_path)
    committee.append(loaded_model)

In [11]:
# Make predictions
committee_predictions = []
for model in committee:
    committee_predictions.append(model.predict(x_test, verbose = 0).reshape(-1)) # Predict the scalar parameter C using the committee   

committee_predictions = np.array(committee_predictions)
y_pred = np.mean(committee_predictions, axis=0)
pred_variance = np.var(committee_predictions, axis=0)
SED_pred = CtoSEDarray(y_pred,pred_variance)


In [12]:
# Evaluate the performance of the committee

mse = np.mean((y_test - y_pred)**2)
print('MSE:', mse)
print("Variance: ", pred_variance)

f1 = f1_score(SED_test, SED_pred, average = None)
f1_mean = np.mean(f1[:13])
print('\nF1 score:', f1)
print('Average F1 score:', f1_mean)

confusion_matrix = tf.math.confusion_matrix(SED_test, SED_pred) 
print("\nConfusion matrix:")
print(confusion_matrix)

success_rate = calculate_success_rate(confusion_matrix)
print('\nSuccess rate:', success_rate)

MSE: 3.531458548152945
Variance:  [4.7369515e-14 3.4058683e-12 3.1405989e-12 ... 8.3701934e-12 2.0463631e-12
 8.1854523e-12]

F1 score: [0.         0.         0.         0.         0.         0.
 0.14255863 0.         0.         0.         0.         0.
 0.        ]
0.010966048114875605

Confusion matrix:
tf.Tensor(
[[   0    0    0    0    0    0 1520    0    0    0    0    0    0]
 [   0    0    0    0    0    0 1526    0    0    0    0    0    0]
 [   0    0    0    0    0    0 1570    0    0    0    0    0    0]
 [   0    0    0    0    0    0 1579    0    0    0    0    0    0]
 [   0    0    0    0    0    0 1515    0    0    0    0    0    0]
 [   0    0    0    0    0    0 1535    0    0    0    0    0    0]
 [   0    0    0    0    0    0 1535    0    0    0    0    0    0]
 [   0    0    0    0    0    0 1569    0    0    0    0    0    0]
 [   0    0    0    0    0    0 1479    0    0    0    0    0    0]
 [   0    0    0    0    0    0 1555    0    0    0    0    0    0]
 [

In [ ]:
#Save the committee models

os.makedirs("committee_models", exist_ok=True)

for i, model in enumerate(committee):
    model.save(f"committee_models/model_{i}.h5")

# Plotting

In [ ]:
import matplotlib.pyplot as plt

In [ ]:
# Plot the confusion matrix

star_class_labels = ['O5','B0','B5','A0','A5','F0','F5','G0','G5','K0','K5','M0','M5']

plt.figure(figsize= (12,10))
heatmap = plt.imshow(confusion_matrix[:13,:], cmap='crest')
plt.xticks(np.arange(14), star_class_labels + ['???'])
plt.yticks(np.arange(13), star_class_labels)
plt.colorbar(heatmap)
plt.xlabel("Estimated spectral type")
plt.ylabel("True spectral type")
plt.show()

In [ ]:
# Plot the metrics

plt.figure(figsize = (9,5))
plt.bar(np.arange(13), height = f1[:13], tick_label = star_class_labels ,label = "F1 score")
plt.axhline(f1_mean, color='red', linestyle='--', label = 'F1 score average')
plt.axhline(success_rate, color='purple', label = 'Success rate')
plt.xlabel("Spectral class")
plt.ylabel("Metric")
plt.legend()

In [ ]:
# PLot the loss function evolution

loss_evolution = learning.history["loss"][10:]
val_loss_evolution = learning.history["val_loss"][10:]

plt.figure(figsize = (9,5))
plt.plot(loss_evolution,label = "Train set")
plt.plot(val_loss_evolution,label = "Validation set")
plt.xlabel("Epochs")
plt.ylabel("Loss function value")
plt.legend()
plt.title("Loss function evolution")
print("Total training time:", training_time, "seconds")
print("Training loss:", loss_evolution[-1], ", Validation loss:", val_loss_evolution[-1])
